# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 12:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text_short', models.TextField(blank=True, null=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('pub_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
            ],
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'BlogTags',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John', max_length=50)),
                ('surname', models.CharField(default='Doe', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='me')),
                ('address', models.CharField(default='Home Sweet Home', max_length=50)),
                ('descript_short', models.CharField(default='hello', max_length=200)),
                ('description', models.TextField(default='kuk', max_length=500)),
                ('birth', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254, verbose_name='John@Doe.com')),
                ('phone', models.CharField(default='777 888 999', max_length=20)),
                ('skype', models.CharField(default='J.D.', max_length=20)),
                ('languages', models.CharField(default='czech', max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='me')),
            ],
            options={
                'verbose_name': 'Me',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Me')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=400)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Me')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Me'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(to='web.Category'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(to='web.BlogTag'),
        ),
    ]
