# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='me',
            options={'verbose_name_plural': 'Me'},
        ),
    ]
