# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 23:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160301_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='birth',
            field=models.DateField(default=datetime.datetime(2016, 2, 29, 23, 54, 21, 189150, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
